name: Streaming-Data-project CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.1

    - name: Install dependencies
      run: |
        make create-environment
        python -m pip install --upgrade pip
        make install-dependencies

    - name: Run tests
      run: |
       make unit-tests || echo "No tests found yet"

    - name: Run code style checks
      run: |
       make run-flake 

    - name: Format code
      run: |
       make run-format

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
        
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: ./infrastructure

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./infrastructure

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
      working-directory: ./infrastructure

    - name: Post Terraform Apply Checks
      if: github.ref == 'refs/heads/main'
      run: terraform output
      working-directory: ./infrastructure